#filebeat.config:
#  modules:
#    path: ${path.config}/modules.d/*.yml
#    reload.enabled: false
filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'


processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["172.31.11.13:9200"]
  username: "elastic"
  password: "ambgam35!"
  indices:
    - index:  "tar-staging-%{+YYYY.MM.dd}"
