filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
- add_cloud_metadata: ~

output.logstash:
  hosts: ["172.31.11.13:5044"]
  username: "elastic"
  password: "ambgam35!"
