#filebeat.config:
#  modules:
#    path: ${path.config}/modules.d/*.yml
#    reload.enabled: false
filebeat.inputs:
#- type: container
#  paths:
#    - '/var/lib/docker/containers/*/*.log'
- type: log
  paths:
    - '/home/ec2-user/amb_redis_tar_latest/logs/*/*.log'

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["172.31.11.13:9200"]
  username: "elastic"
  password: "ambgam35!"
  indices:
    - index:  "tar-staging-%{+YYYY.MM.dd}"
